image: node:16-alpine
stages:
  - setup
  - build

install-dependencies:
  stage: setup
  interruptible: true
  only:
    - main
    - merge_requests
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
      - .yarn
  script:
    - yarn install --pure-lockfile --cache-folder .yarn
  artifacts:
    paths:
      - node_modules

build wh:
  stage: build
  script:
    - yarn build:client
  artifacts:
    paths:
      - dist/while-hungry
    expire_in: 50 minutes

# build api:
#   stage: build
#   script:
#     - yarn build:api
#   artifacts:
#     paths:
#       - dist/api
#     expire_in: 50 minutes



