image: mhart/alpine-node:16.10
stages:
  - setup
  - lint
  - build

cache: &global_cache
  paths:
    - node_modules/
    - .env
  policy: pull

install-dependencies:
  stage: setup
  interruptible: true
  only:
    - main
    - merge_requests
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
      - .yarn
  script:
    - yarn install --pure-lockfile --cache-folder .yarn
  artifacts:
    paths:
      - node_modules
    expire_in: 50 minutes


#lint stages
lint api:
  stage: lint
  script:
    - yarn lint:api

lint school:
  stage: lint
  script:
    - yarn lint:client

#build stages
build api:
  stage: build
  script:
    - yarn build:api
  artifacts:
    paths:
      - dist/api
    expire_in: 50 minutes

build wh:
  stage: build
  script:
    - yarn build:client
  artifacts:
    paths:
      - dist/while-hungry
    expire_in: 50 minutes

