image: mhart/alpine-node:16

stages:
  - setup
  - build

cache: &global_cache
  paths:
    - node_modules/
    - .env
  policy: pull


install:
  stage: setup
  interruptible: true
  only:
    - main
    - merge_requests
  cache:
    <<: *global_cache
    #overide the policy
    policy: pull-push
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules


build wh:
  stage: build
  script:
    - yarn build:client
  artifacts:
    paths:
      - dist/while-hungry
    expire_in: 50 minutes



# build wh:
#   stage: build
#   script:
#     - yarn build:client
#   artifacts:
#     paths:
#       - dist/apps/while-hungry
#     expire_in: 50 minutes

# build api:
#   stage: build
#   script:
#     - yarn build:api
#   artifacts:
#     paths:
#       - dist/api
#     expire_in: 50 minutes



