image: node:16

before_script:
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
  - chmod 700 ~/.ssh/id_ed25519
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_ed25519
  - ssh-keyscan -t ed25519 152.228.218.72 > ~/.ssh/known_hosts
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - chmod 644 ~/.ssh/known_hosts

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .env
  policy: pull

stages:
  - setup
  - build
  - deploy

install:
  stage: setup
  interruptible: true
  only:
    - main
    - merge_requests
  cache:
    <<: *global_cache
    #overide the policy
    policy: pull-push
  script:
    - npm run install
  artifacts:
    paths:
      - node_modules

build front:
  stage: build
  script:
    - npm run build:client
  artifacts:
    paths:
      - ./dist/apps/while-hungry
    expire_in: 50 mins
  only:
    - main
    - merge_requests

build api:
  stage: build
  script:
    - npm run build:api
  artifacts:
    paths:
      - ./dist/apps/api
    expire_in: 50 minutes

deploy_main:
  stage: deploy
  variables:
    SERVEUR: "nasfernane@152.228.218.72"
    CHEMIN: "/var/www/html/"
  script:
    - which rsync || ( apt update -y && apt install rsync -y )
    - ls -la
    - ls -la ./dist/apps/
    - /sbin/ip route|awk '/default/ { print $3 }'
    - ls ./dist/apps/
    - /usr/bin/rsync -r ./dist/apps/while-hungry/ ${SERVEUR}:${CHEMIN}. --exclude-from="exclude.build"
  only:
    - main
