image: node:17

variables:
  WH_ENV: $CI_COMMIT_REF_NAME
  PORT: $PORT
  GIT_DEPTH: 5
  DATABASE_URL: $CI_COMMIT_REF_NAME
  SHADOW_DATABASE_URL: $CI_COMMIT_REF_NAME
  ACCESS_TOKEN_SECRET: $CI_COMMIT_REF_NAME
  WH_DOCKER_IMAGE: $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
  WH_DOCKER_HOST: gcr.io
 

stages:
  - setup
  - lint
  - build
  - dockerize
  - deploy

cache: &global_cache
  paths:
    - node_modules/
    - .env
  policy: pull


install:
  stage: setup
  interruptible: true
  only:
    - main
    - merge_requests
  cache:
    <<: *global_cache
    #overide the policy
    policy: pull-push
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules

#lint stages
lint api:
  stage: lint
  script:
    - yarn lint:api

lint school:
  stage: lint
  script:
    - yarn lint:client

build wh:
  stage: build
  script:
    - yarn build:client
  artifacts:
    paths:
      - dist/while-hungry
    expire_in: 50 minutes

build api:
  stage: build
  script:
    - yarn build:api
  artifacts:
    paths:
      - dist/api
    expire_in: 50 minutes

generate image:
  stage: dockerize
  image: docker:19.03.1
  dependencies:
    - build wh
    - build api
  services:
    - docker:19.03.1-dind
  script:
    - docker build -t $WH_DOCKER_IMAGE .








