image: node:17

variables:
  NODE_ENV: $NODE_ENV
  PORT: $PORT
  DATABASE_URL: $DATABASE_URL
  SHADOW_DATABASE_URL: $SHADOW_DATABASE_URL
  ACCESS_TOKEN_SECRET: $ACCESS_TOKEN_SECRET
 

stages:
  - setup
  - lint
  - build

cache: &global_cache
  paths:
    - node_modules/
    - .env
  policy: pull


install:
  stage: setup
  interruptible: true
  only:
    - main
    - merge_requests
  cache:
    <<: *global_cache
    #overide the policy
    policy: pull-push
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules

#lint stages
lint api:
  stage: lint
  script:
    - yarn lint:api

lint school:
  stage: lint
  script:
    - yarn lint:client



build wh:
  stage: build
  script:
    - yarn build:client
  artifacts:
    paths:
      - dist/while-hungry
    expire_in: 50 minutes

build api:
  stage: build
  script:
    - yarn build:api
  artifacts:
    paths:
      - dist/api
    expire_in: 50 minutes






