image: node:16

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
  - chmod 700 ~/.ssh/id_ed25519
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_ed25519
  - ssh-keyscan -t ed25519 152.228.218.72 > ~/.ssh/known_hosts
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - chmod 644 ~/.ssh/known_hosts

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .env
  policy: pull

stages:
  - setup
  - lint
  - build
  - deploy

install:
  stage: setup
  interruptible: true
  only:
    - main
    - merge_requests
  cache:
    <<: *global_cache
    #overide the policy
    policy: pull-push
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

lint front:
  stage: lint
  script:
    - npm run lint:web
  only:
    - main
    - merge_requests

lint api:
  stage: lint
  script:
    - npm run lint:api
  only:
    - main
    - merge_requests

build front:
  stage: build
  script:
    - npm run build:web
  artifacts:
    paths:
      - ./dist/apps/while-hungry
    expire_in: 50 mins
  only:
    - main
    - merge_requests

build api:
  stage: build
  script:
    - npm run build:api
  artifacts:
    paths:
      - ./dist/apps/api
    expire_in: 50 minutes
  only:
    - main
    - merge_requests

deploy_main:
  stage: deploy
  variables:
    SERVER: 'nasfernane@152.228.218.72'
    WEB_PATH: '/var/www/www.whilehungry.com/'
    API_PATH: '/home/nasfernane/while-hungry/dist/apps/api/'
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    # check installs
    - which rsync || ( apt update -y && apt install rsync -y )
    # push front
    - /usr/bin/rsync -r ./dist/apps/while-hungry/ ${SERVER}:${WEB_PATH}. --exclude-from="exclude.build"
    # push and deploy back
    - /usr/bin/rsync -r ./dist/apps/api/ ${SERVER}:${API_PATH}.
    # - "pm2 start ecosystem.config.js"
    - "pm2 restart wh-api"
    # - "pm2 start npm --name wh-api --"
  only:
    - main
    - merge_requests
